# Generated by Django 4.2.5 on 2023-10-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='short_info',
            field=models.TextField(default='short info'),
        ),
    ]
