# Generated by Django 4.2.5 on 2023-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_car_short_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.TextField(default='Automatic'),
        ),
        migrations.AddField(
            model_name='car',
            name='traction',
            field=models.TextField(default='N/A'),
        ),
    ]
