# Generated by Django 4.2.5 on 2023-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_car_mileage_car_price_month_car_stock_car_vin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='fuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='type',
        ),
        migrations.AddField(
            model_name='car',
            name='body_color',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.TextField(default='N/A'),
        ),
    ]
