# Generated by Django 4.2.5 on 2023-11-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_car_fuel_remove_car_type_car_body_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='shorter_info',
            field=models.TextField(default='N/A'),
        ),
    ]
