# Generated by Django 4.2.5 on 2023-11-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_car_shorter_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo_test_main',
            field=models.TextField(default='N/A'),
        ),
    ]
