# Generated by Django 4.2.5 on 2023-11-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_car_photo_test_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video_link',
            field=models.TextField(default='<iframe width="1029" height="579" src="https://www.youtube.com/embed/BcJN9JGaYFQ" title="1977 CHEVROLET K20" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>'),
        ),
    ]
