# Generated by Django 4.2.5 on 2023-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_car_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='carphoto',
            name='photo1',
            field=models.TextField(default='https://cdn.dealeraccelerate.com/worldwide/1/8226/510832/1920x1440/w/1986-mercedes-benz-560sl'),
        ),
    ]
