# Generated by Django 4.2.5 on 2023-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_carphoto_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video_photo',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/YouTube_full-color_icon_%282017%29.svg/1024px-YouTube_full-color_icon_%282017%29.svg.png'),
        ),
    ]
